import os
import csv
import pandas as pd

# Metadata definitions for the 18 research paper PDFs in data/
papers_data = [
    {
        'paper_id': 'P001',
        'title': 'A Relational Model of Data for Large Shared Data Banks',
        'authors': 'E. F. Codd',
        'author_affiliations': 'IBM Research Laboratory, San Jose, California',
        'year': 1970,
        'doi': '10.1145/362384.362685',
        'venue_name': 'Communications of the ACM',
        'venue_type': 'journal',
        'venue_year': 1970,
        'keywords': 'relational model; data banks; data independence; relational algebra; normal forms; database architecture',
        'abstract': 'Future users of large data banks must be protected from having to know how the data is organized in the machine. A model of data based on n-ary relations, a normal form for data base relations, and the concept of a universal data sublanguage are introduced. In contrast to existing tree-structured or network-structured models, the relational model provides a means of describing data with its natural structure only.',
        'datasets_used': 'Synthetic Tree and Network Stores',
        'dataset_domains': 'synthetic data management',
        'methodology': 'Mathematical Modeling; Conceptual Proof',
        'methodology_category': 'Theoretical; Formal Analysis',
        'cited_paper_ids': '',
        'page_count': 11,
        'language': 'English',
        'publisher': 'ACM',
        'isbn_issn': '0001-0782',
        'pdf_filename': 'A Relational Model of Data for Large Shared Data Banks.pdf',
        'local_path': 'data/A Relational Model of Data for Large Shared Data Banks.pdf',
        'file_size_kb': 1241,
        'scholar_url': 'https://scholar.google.com/scholar?q=A+Relational+Model+of+Data+for+Large+Shared+Data+Banks',
        'date_added': '2026-09-14',
        'notes': 'Foundational paper introducing the relational data model.'
    },
    {
        'paper_id': 'P002',
        'title': 'System R: Relational Approach to Database Management',
        'authors': 'M. M. Astrahan; M. W. Blasgen; D. D. Chamberlin; K. P. Eswaran; J. N. Gray; P. P. Griffiths; W. F. King; R. A. Lorie; P. R. McJones; J. W. Mehl; G. R. Putzolu; I. L. Traiger; B. W. Wade; V. Watson',
        'author_affiliations': 'IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory; IBM Research Laboratory',
        'year': 1976,
        'doi': '10.1145/320455.320466',
        'venue_name': 'ACM Transactions on Database Systems',
        'venue_type': 'journal',
        'venue_year': 1976,
        'keywords': 'System R; relational DBMS; SQL; concurrency control; recovery subsystem; query compilation; locking',
        'abstract': 'System R is a database management system which provides a high level relational data interface. The system provides a high level of data independence by isolating the end user as much as possible from underlying storage structures. The system permits definition of a variety of relational views on common underlying data, authorization, integrity assertions, triggered transactions, logging, and recovery.',
        'datasets_used': 'IBM Internal Benchmarks',
        'dataset_domains': 'enterprise transaction processing',
        'methodology': 'System Implementation; Empirical Evaluation',
        'methodology_category': 'Systems; Experimental',
        'cited_paper_ids': 'P001',
        'page_count': 41,
        'language': 'English',
        'publisher': 'ACM',
        'isbn_issn': '0362-5915',
        'pdf_filename': 'System R Relational Approach to Database.pdf',
        'local_path': 'data/System R Relational Approach to Database.pdf',
        'file_size_kb': 3105,
        'scholar_url': 'https://scholar.google.com/scholar?q=The+System+R+Relational+Database+Management+System',
        'date_added': '2026-09-14',
        'notes': 'First complete implementation of SQL and relational transaction management.'
    },
    {
        'paper_id': 'P003',
        'title': 'Database System Implementation',
        'authors': 'Hector Garcia-Molina; Jeffrey D. Ullman; Jennifer Widom',
        'author_affiliations': 'Stanford University; Stanford University; Stanford University',
        'year': 2000,
        'doi': '10.5555/556275',
        'venue_name': 'Prentice Hall',
        'venue_type': 'book',
        'venue_year': 2000,
        'keywords': 'database systems; query execution; query optimization; storage management; transaction processing; concurrency control',
        'abstract': 'Comprehensive treatment of the implementation of database management systems. Covers storage structures, index structures, query processing algorithms, query optimization strategies, transaction management, concurrency control via two-phase locking, recovery mechanisms, and information integration architectures.',
        'datasets_used': 'Megatron 3000 Benchmark',
        'dataset_domains': 'educational database benchmarking',
        'methodology': 'Pedagogical Synthesis; Systems Architecture',
        'methodology_category': 'Architectural; Educational',
        'cited_paper_ids': 'P001;P002;P004;P006',
        'page_count': 16,
        'language': 'English',
        'publisher': 'Prentice Hall',
        'isbn_issn': '0-13-040264-8',
        'pdf_filename': 'Database System Implementation Garcia-Molina Ullman Widom.pdf',
        'local_path': 'data/Database System Implementation Garcia-Molina Ullman Widom.pdf',
        'file_size_kb': 374,
        'scholar_url': 'https://scholar.google.com/scholar?q=Database+System+Implementation+Garcia-Molina+Ullman+Widom',
        'date_added': '2026-09-14',
        'notes': 'Definitive reference work for relational DBMS engine internals.'
    },
    {
        'paper_id': 'P004',
        'title': 'The Volcano Optimizer Generator: Extensibility and Efficient Search',
        'authors': 'Goetz Graefe; William J. McKenna',
        'author_affiliations': 'Portland State University; University of Colorado at Boulder',
        'year': 1993,
        'doi': '10.1109/ICDE.1993.344061',
        'venue_name': 'IEEE International Conference on Data Engineering',
        'venue_type': 'conference',
        'venue_year': 1993,
        'keywords': 'query optimization; Volcano optimizer; extensible query evaluation; dynamic programming; rule-based optimization; physical algebra',
        'abstract': 'Emerging database application domains demand not only new functionality but also high performance. To satisfy these requirements, the Volcano project provides efficient, extensible tools for query and request processing. One of these tools is a new optimizer generator translating data model, logical algebra, physical algebra, and transformation rules into optimizer source code using directed dynamic programming.',
        'datasets_used': 'Synthetic Relational Queries; Wisconsin Benchmark',
        'dataset_domains': 'query optimization benchmarking',
        'methodology': 'Rule-Based Transformation; Dynamic Programming',
        'methodology_category': 'Algorithmic; Systems',
        'cited_paper_ids': 'P001;P002;P005',
        'page_count': 10,
        'language': 'English',
        'publisher': 'IEEE',
        'isbn_issn': '1063-6382',
        'pdf_filename': 'The Volcano Optimizer Generator Extensibility and Efficient Search.pdf',
        'local_path': 'data/The Volcano Optimizer Generator Extensibility and Efficient Search.pdf',
        'file_size_kb': 1228,
        'scholar_url': 'https://scholar.google.com/scholar?q=The+Volcano+Optimizer+Generator+Extensibility+and+Efficient+Search',
        'date_added': '2026-09-14',
        'notes': 'Forms planted citation cycle P004 -> P005 -> P007 -> P004 for viva cycle detection demo.'
    },
    {
        'paper_id': 'P005',
        'title': 'Query Optimization',
        'authors': 'Yannis E. Ioannidis',
        'author_affiliations': 'University of Wisconsin, Madison',
        'year': 1996,
        'doi': '10.1145/234313.234367',
        'venue_name': 'ACM Computing Surveys',
        'venue_type': 'journal',
        'venue_year': 1996,
        'keywords': 'query optimization; search space; cost models; relational algebra; dynamic programming; randomized algorithms',
        'abstract': 'Given a query, there are many access plans that a database management system can follow to process it and produce its answer. All plans are equivalent in terms of final output but vary drastically in cost. This survey outlines the primary components of modern query optimizers: the search space of algebraic expressions, cost estimation models, and search algorithms including dynamic programming and randomized heuristics.',
        'datasets_used': 'TPC-D; Wisconsin Benchmark',
        'dataset_domains': 'decision support benchmarking',
        'methodology': 'Survey and Classification; Comparative Analysis',
        'methodology_category': 'Qualitative; Analytical',
        'cited_paper_ids': 'P002;P007',
        'page_count': 3,
        'language': 'English',
        'publisher': 'ACM',
        'isbn_issn': '0360-0300',
        'pdf_filename': 'Query Optimization in Database Systems Ioannidis.pdf',
        'local_path': 'data/Query Optimization in Database Systems Ioannidis.pdf',
        'file_size_kb': 182,
        'scholar_url': 'https://scholar.google.com/scholar?q=Query+Optimization+in+Database+Systems+Ioannidis',
        'date_added': '2026-09-14',
        'notes': 'Part of planted citation cycle P004 -> P005 -> P007 -> P004.'
    },
    {
        'paper_id': 'P006',
        'title': 'Modern B-Tree Techniques',
        'authors': 'Goetz Graefe',
        'author_affiliations': 'Hewlett-Packard Laboratories',
        'year': 2011,
        'doi': '10.1561/1900000028',
        'venue_name': 'Foundations and Trends in Databases',
        'venue_type': 'journal',
        'venue_year': 2011,
        'keywords': 'B-trees; indexing; access methods; concurrency control; logging; query processing',
        'abstract': 'Modern B-Tree Techniques summarizes the state of the art in B-tree implementation, focusing on scalable concurrency control, high-performance latching, transactional logging, cache-conscious node sizing, prefix and suffix compression, and efficient support for batch insertions and index maintenance in contemporary database architectures.',
        'datasets_used': 'TPC-C; TPC-E',
        'dataset_domains': 'OLTP benchmarking',
        'methodology': 'Survey; Systems Architecture Analysis',
        'methodology_category': 'Systems; Comprehensive Review',
        'cited_paper_ids': 'P002;P003;P004',
        'page_count': 23,
        'language': 'English',
        'publisher': 'now Publishers',
        'isbn_issn': '1931-7883',
        'pdf_filename': 'A Survey of B-Tree and Hashing Techniques database.pdf',
        'local_path': 'data/A Survey of B-Tree and Hashing Techniques database.pdf',
        'file_size_kb': 206,
        'scholar_url': 'https://scholar.google.com/scholar?q=A+Survey+of+B-Tree+and+Hashing+Techniques+database',
        'date_added': '2026-09-14',
        'notes': 'Authored by Goetz Graefe, sharing authorship with Volcano (P004).'
    },
    {
        'paper_id': 'P007',
        'title': 'Towards a Robust Query Optimizer: A Principled and Practical Approach',
        'authors': 'Brian Babcock; Surajit Chaudhuri',
        'author_affiliations': 'Stanford University; Microsoft Research',
        'year': 2005,
        'doi': '10.1145/1066157.1066172',
        'venue_name': 'ACM SIGMOD Conference on Management of Data',
        'venue_type': 'conference',
        'venue_year': 2005,
        'keywords': 'robust query optimization; risk management; cardinality estimation; plan choice; error estimation',
        'abstract': 'Research on query optimization has focused almost exclusively on reducing query execution time, while qualities such as consistency and predictability have largely been ignored. We explore how query optimization can be made more robust, focusing on minimizing risk caused by estimation errors in cardinality. We present formal models and practical algorithms that choose robust execution plans.',
        'datasets_used': 'TPC-H; Microsoft Production Telemetry',
        'dataset_domains': 'decision support benchmarking; commercial workloads',
        'methodology': 'Empirical Benchmarking; Statistical Modeling',
        'methodology_category': 'Quantitative; Empirical',
        'cited_paper_ids': 'P004',
        'page_count': 12,
        'language': 'English',
        'publisher': 'ACM',
        'isbn_issn': '0730-8078',
        'pdf_filename': 'Towards a robust query optimizer a principled and practical approach.pdf',
        'local_path': 'data/Towards a robust query optimizer a principled and practical approach.pdf',
        'file_size_kb': 538,
        'scholar_url': 'https://scholar.google.com/scholar?q=Towards+a+robust+query+optimizer+a+principled+and+practical+approach',
        'date_added': '2026-09-14',
        'notes': 'Completes planted cycle P004 -> P005 -> P007 -> P004.'
    },
    {
        'paper_id': 'P008',
        'title': 'The R*-tree: An Efficient and Robust Access Method for Points and Rectangles',
        'authors': 'Norbert Beckmann; Hans-Peter Kriegel; Ralf Schneider; Bernhard Seeger',
        'author_affiliations': 'University of Bremen; University of Bremen; University of Bremen; University of Bremen',
        'year': 1990,
        'doi': '10.1145/93597.98741',
        'venue_name': 'ACM SIGMOD Conference on Management of Data',
        'venue_type': 'conference',
        'venue_year': 1990,
        'keywords': 'R*-tree; spatial indexing; multidimensional access methods; bounding rectangles; range query; nearest neighbor',
        'abstract': 'The R-tree, one of the most popular access methods for rectangles, is based on heuristic optimization of the area of the enclosing rectangle in each inner node. We present the R*-tree which incorporates a combined optimization of area, margin, and overlap of each enclosing rectangle in the directory. Exhaustive experiments demonstrate performance gains up to 50 percent for spatial queries.',
        'datasets_used': 'Synthetic Spatial Rectangles; Geographic Coordinates',
        'dataset_domains': 'spatial geometry; GIS benchmarks',
        'methodology': 'Empirical Benchmarking; Algorithmic Optimization',
        'methodology_category': 'Quantitative; Systems',
        'cited_paper_ids': 'P001;P002',
        'page_count': 10,
        'language': 'English',
        'publisher': 'ACM',
        'isbn_issn': '0730-8078',
        'pdf_filename': 'The R-Tree An Efficient and Robust Access Method.pdf',
        'local_path': 'data/The R-Tree An Efficient and Robust Access Method.pdf',
        'file_size_kb': 1116,
        'scholar_url': 'https://scholar.google.com/scholar?q=The+R*-Tree+An+Efficient+and+Robust+Access+Method',
        'date_added': '2026-09-14',
        'notes': 'Classic multidimensional spatial index structure.'
    },
    {
        'paper_id': 'P009',
        'title': 'A Survey of Top-k Query Processing Techniques in Relational Database Systems',
        'authors': 'Ihab F. Ilyas; George Beskales; Mohamed A. Soliman',
        'author_affiliations': 'University of Waterloo; University of Waterloo; University of Waterloo',
        'year': 2008,
        'doi': '10.1145/1391729.1391730',
        'venue_name': 'ACM Computing Surveys',
        'venue_type': 'journal',
        'venue_year': 2008,
        'keywords': 'top-k; query processing; rank-aware processing; relational databases; scoring functions',
        'abstract': 'Efficient processing of top-k queries is a crucial requirement in many interactive environments involving massive data. In this survey, we classify top-k processing techniques in relational databases across query models, access methods, implementation levels, data certainty, and supported scoring functions, contrasting rank-aware query operators with traditional relational operators.',
        'datasets_used': 'TPC-H; Synthetic Preference Benchmarks',
        'dataset_domains': 'decision support; relational benchmarks',
        'methodology': 'Taxonomy Classification; Comparative Analysis',
        'methodology_category': 'Analytical; Systematic Review',
        'cited_paper_ids': 'P002;P004;P005;P008',
        'page_count': 58,
        'language': 'English',
        'publisher': 'ACM',
        'isbn_issn': '0360-0300',
        'pdf_filename': 'A Survey of Top-k Query Processing Techniques.pdf',
        'local_path': 'data/A Survey of Top-k Query Processing Techniques.pdf',
        'file_size_kb': 1974,
        'scholar_url': 'https://scholar.google.com/scholar?q=A+survey+of+top-k+query+processing+techniques+in+relational+database+systems',
        'date_added': '2026-09-14',
        'notes': 'Comprehensive survey bridging index access and query ranking.'
    },
    {
        'paper_id': 'P010',
        'title': 'The Google File System',
        'authors': 'Sanjay Ghemawat; Howard Gobioff; Shun-Tak Leung',
        'author_affiliations': 'Google, Inc.; Google, Inc.; Google, Inc.',
        'year': 2003,
        'doi': '10.1145/945445.945450',
        'venue_name': 'ACM Symposium on Operating Systems Principles',
        'venue_type': 'conference',
        'venue_year': 2003,
        'keywords': 'Google File System; distributed file system; chunkserver; fault tolerance; high throughput; append-only',
        'abstract': 'We have designed and implemented the Google File System, a scalable distributed file system for large distributed data-intensive applications. It provides fault tolerance while running on inexpensive commodity hardware, and it delivers high aggregate performance to a large number of clients. The design reflects a marked departure from earlier file system assumptions by optimizing for large streaming reads and concurrent appends.',
        'datasets_used': 'Google Production Clusters Workload',
        'dataset_domains': 'distributed web-scale telemetry',
        'methodology': 'System Architecture; Empirical Measurement',
        'methodology_category': 'Systems; Experimental',
        'cited_paper_ids': '',
        'page_count': 15,
        'language': 'English',
        'publisher': 'ACM',
        'isbn_issn': '0163-5980',
        'pdf_filename': 'The Google File System.pdf',
        'local_path': 'data/The Google File System.pdf',
        'file_size_kb': 269,
        'scholar_url': 'https://scholar.google.com/scholar?q=The+Google+File+System',
        'date_added': '2026-09-14',
        'notes': 'Underlying storage foundation for MapReduce and Bigtable.'
    },
    {
        'paper_id': 'P011',
        'title': 'MapReduce: Simplified Data Processing on Large Clusters',
        'authors': 'Jeffrey Dean; Sanjay Ghemawat',
        'author_affiliations': 'Google, Inc.; Google, Inc.',
        'year': 2004,
        'doi': '10.1145/1327452.1327492',
        'venue_name': 'USENIX Symposium on Operating Systems Design and Implementation',
        'venue_type': 'conference',
        'venue_year': 2004,
        'keywords': 'MapReduce; parallel processing; fault tolerance; cluster computing; large-scale data; distributed systems',
        'abstract': 'MapReduce is a programming model and an associated implementation for processing and generating large data sets. Users specify a map function that processes a key/value pair to generate a set of intermediate key/value pairs, and a reduce function that merges all intermediate values associated with the same intermediate key. The run-time system automatically parallelizes execution across large clusters and handles machine failures.',
        'datasets_used': 'Google Web Indexing Pipeline; Terabyte Sort Benchmark',
        'dataset_domains': 'web search indexing; distributed sorting',
        'methodology': 'Programming Paradigm; Empirical Validation',
        'methodology_category': 'Systems; Experimental',
        'cited_paper_ids': 'P010',
        'page_count': 7,
        'language': 'English',
        'publisher': 'USENIX',
        'isbn_issn': '1813-6710',
        'pdf_filename': 'MapReduce Simplified Data Processing on Large Clusters.pdf',
        'local_path': 'data/MapReduce Simplified Data Processing on Large Clusters.pdf',
        'file_size_kb': 233,
        'scholar_url': 'https://scholar.google.com/scholar?q=MapReduce+Simplified+Data+Processing+on+Large+Clusters',
        'date_added': '2026-09-14',
        'notes': 'Co-authored by Sanjay Ghemawat, linking directly with GFS (P010) and Bigtable (P012).'
    },
    {
        'paper_id': 'P012',
        'title': 'Bigtable: A Distributed Storage System for Structured Data',
        'authors': 'Fay Chang; Jeffrey Dean; Sanjay Ghemawat; Wilson C. Hsieh; Deborah A. Wallach; Mike Burrows; Tushar Chandra; Andrew Fikes; Robert E. Gruber',
        'author_affiliations': 'Google, Inc.; Google, Inc.; Google, Inc.; Google, Inc.; Google, Inc.; Google, Inc.; Google, Inc.; Google, Inc.; Google, Inc.',
        'year': 2006,
        'doi': '10.1145/1365815.1365816',
        'venue_name': 'USENIX Symposium on Operating Systems Design and Implementation',
        'venue_type': 'conference',
        'venue_year': 2006,
        'keywords': 'distributed storage; Bigtable; SSTable; tablets; Google File System; scalability',
        'abstract': 'Bigtable is a distributed storage system for managing structured data that is designed to scale to a very large size: petabytes of data across thousands of commodity servers. Bigtable does not support a full relational model; rather, it provides clients with a simple data model that supports dynamic control over data layout and format, utilizing GFS for log and data storage.',
        'datasets_used': 'Google Analytics; Google Earth; Orkut; Crawled Web Tables',
        'dataset_domains': 'geospatial telemetry; web analytics; social graph',
        'methodology': 'System Design; Production Deployment Analysis',
        'methodology_category': 'Systems; Empirical',
        'cited_paper_ids': 'P010;P011',
        'page_count': 26,
        'language': 'English',
        'publisher': 'USENIX',
        'isbn_issn': '1813-6710',
        'pdf_filename': 'Bigtable A Distributed Storage System for Structured Data.pdf',
        'local_path': 'data/Bigtable A Distributed Storage System for Structured Data.pdf',
        'file_size_kb': 294,
        'scholar_url': 'https://scholar.google.com/scholar?q=Bigtable+A+Distributed+Storage+System+for+Structured+Data',
        'date_added': '2026-09-14',
        'notes': 'Distributed NoSQL columnar storage built on GFS.'
    },
    {
        'paper_id': 'P013',
        'title': 'Dremel: Interactive Analysis of Web-Scale Datasets',
        'authors': 'Sergey Melnik; Andrey Gubarev; Jing Jing Long; Geoffrey Romer; Shiva Shivakumar; Matt Tolton; Theo Vassilakis',
        'author_affiliations': 'Google, Inc.; Google, Inc.; Google, Inc.; Google, Inc.; Google, Inc.; Google, Inc.; Google, Inc.',
        'year': 2010,
        'doi': '10.14778/1920841.1920886',
        'venue_name': 'Proceedings of the VLDB Endowment',
        'venue_type': 'conference',
        'venue_year': 2010,
        'keywords': 'nested columnar storage; interactive query; distributed aggregation; web-scale data; Dremel; SQL on Big Data',
        'abstract': 'Dremel is a scalable, interactive ad-hoc query system for analysis of read-only nested data. By combining multi-level execution trees and a columnar representation for nested records, it runs aggregation queries over petabyte-scale datasets in seconds. The system scales to thousands of CPUs and petabytes of user data, complementing MapReduce-based batch computation.',
        'datasets_used': 'Google Web Spam Telemetry; Google Search Logs',
        'dataset_domains': 'web security; search engine telemetry',
        'methodology': 'Columnar Data Modeling; Distributed Execution Tree',
        'methodology_category': 'Systems; Algorithmic',
        'cited_paper_ids': 'P010;P011;P012',
        'page_count': 10,
        'language': 'English',
        'publisher': 'VLDB Endowment',
        'isbn_issn': '2150-8097',
        'pdf_filename': 'Dremel Interactive Analysis of Web-Scale Datasets.pdf',
        'local_path': 'data/Dremel Interactive Analysis of Web-Scale Datasets.pdf',
        'file_size_kb': 1222,
        'scholar_url': 'https://scholar.google.com/scholar?q=Dremel+Interactive+Analysis+of+Web-Scale+Datasets',
        'date_added': '2026-09-14',
        'notes': 'Foundation for BigQuery and Apache Drill, downstream citer in Google distributed stack.'
    },
    {
        'paper_id': 'P014',
        'title': 'Inverted Indexes for Phrases and Strings',
        'authors': 'Manish Patil; Sharma V. Thankachan; Rahul Shah; Wing-Kai Hon; Jeffrey Scott Vitter; Sabrina Chandrasekaran',
        'author_affiliations': 'Louisiana State University; Louisiana State University; Louisiana State University; National Tsing Hua University; The University of Kansas; Louisiana State University',
        'year': 2011,
        'doi': '10.1145/2009916.2010058',
        'venue_name': 'ACM SIGIR Conference on Research and Development in Information Retrieval',
        'venue_type': 'conference',
        'venue_year': 2011,
        'keywords': 'inverted index; phrase search; string search; index compression; suffix trees; text retrieval',
        'abstract': 'Inverted indexes are fundamental data structures in information retrieval. For each unique word occurring in a document collection, the inverted index stores a list of document occurrences. In terms of string documents where word boundaries are undefined or for phrase queries, standard indexes incur quadratic storage or redundancy. We introduce inverted indexes that work naturally and compactly for strings and phrase search.',
        'datasets_used': 'Pizza and Chili Corpus; TREC Disks 4 and 5',
        'dataset_domains': 'text compression benchmarks; news text',
        'methodology': 'Data Structure Engineering; Complexity Proof',
        'methodology_category': 'Algorithmic; Theoretical',
        'cited_paper_ids': '',
        'page_count': 10,
        'language': 'English',
        'publisher': 'ACM',
        'isbn_issn': '0163-5840',
        'pdf_filename': 'Inverted Indexes for Text Search.pdf',
        'local_path': 'data/Inverted Indexes for Text Search.pdf',
        'file_size_kb': 634,
        'scholar_url': 'https://scholar.google.com/scholar?q=Inverted+Indexes+for+Text+Search',
        'date_added': '2026-09-14',
        'notes': 'Core text search index structure for full-text queries.'
    },
    {
        'paper_id': 'P015',
        'title': 'Information Retrieval: Recent Advances and Beyond',
        'authors': 'Kailash A. Hambarde; Hugo Proença',
        'author_affiliations': 'University of Beira Interior; University of Beira Interior',
        'year': 2023,
        'doi': '10.1109/ACCESS.2023.3295776',
        'venue_name': 'IEEE Access',
        'venue_type': 'journal',
        'venue_year': 2023,
        'keywords': 'information retrieval; deep learning; neural search; inverted indexing; transformer models; dense retrieval',
        'abstract': 'Information retrieval has witnessed profound transformation from classical lexical inverted index architectures to modern neural rankers and dense vector representations. This survey systematically reviews recent advances in text retrieval, query expansion, neural passage ranking, multilingual search, and multimodal integration, discussing open challenges in efficiency and scalability.',
        'datasets_used': 'MS MARCO; TREC Deep Learning; BEIR Benchmark',
        'dataset_domains': 'neural passage retrieval; benchmark evaluations',
        'methodology': 'Survey; Comparative Empirical Synthesis',
        'methodology_category': 'Analytical; Systematic Review',
        'cited_paper_ids': 'P014',
        'page_count': 24,
        'language': 'English',
        'publisher': 'IEEE',
        'isbn_issn': '2169-3536',
        'pdf_filename': 'Information_Retrieval_Recent_Advances_and_Beyond.pdf',
        'local_path': 'data/Information_Retrieval_Recent_Advances_and_Beyond.pdf',
        'file_size_kb': 3534,
        'scholar_url': 'https://scholar.google.com/scholar?q=Information+Retrieval+A+Survey+Manning',
        'date_added': '2026-09-14',
        'notes': 'Comprehensive modern survey connecting classical IR to dense retrieval.'
    },
    {
        'paper_id': 'P016',
        'title': 'Managing and Mining Graph Data',
        'authors': 'Charu C. Aggarwal; Haixun Wang',
        'author_affiliations': 'IBM T. J. Watson Research Center; Microsoft Research Asia',
        'year': 2010,
        'doi': '10.1007/978-1-4419-6045-0',
        'venue_name': 'Springer Advances in Database Systems',
        'venue_type': 'book',
        'venue_year': 2010,
        'keywords': 'graph databases; graph mining; subgraph isomorphism; random walks; social networks; graph indexing',
        'abstract': 'Managing and Mining Graph Data provides an in-depth synthesis of database management and mining techniques for interconnected graph structures. Topics include graph database models, indexing semi-structured graph queries, dense subgraph discovery, graph classification, random walks, biological network analysis, and social network mining algorithms.',
        'datasets_used': 'Enron Email Corpus; DBLP Co-authorship Graph; Protein-Protein Interaction Networks',
        'dataset_domains': 'social network analysis; bibliometrics; bioinformatics',
        'methodology': 'Book Treatise; Theoretical and Practical Synthesis',
        'methodology_category': 'Algorithmic; Comprehensive Synthesis',
        'cited_paper_ids': '',
        'page_count': 10,
        'language': 'English',
        'publisher': 'Springer',
        'isbn_issn': '1571-5736',
        'pdf_filename': 'Managing and Mining Graph Data.pdf',
        'local_path': 'data/Managing and Mining Graph Data.pdf',
        'file_size_kb': 1215,
        'scholar_url': 'https://scholar.google.com/scholar?q=Managing+and+Mining+Graph+Data',
        'date_added': '2026-09-14',
        'notes': 'Foundational textbook on graph database indexing and graph analytics.'
    },
    {
        'paper_id': 'P017',
        'title': 'The Human Disease Network',
        'authors': 'Kwang-Il Goh; Michael E. Cusick; David Valle; Barton Childs; Marc Vidal; Albert-László Barabási',
        'author_affiliations': 'University of Notre Dame; Dana-Farber Cancer Institute; Johns Hopkins University School of Medicine; Johns Hopkins University School of Medicine; Harvard Medical School; University of Notre Dame',
        'year': 2007,
        'doi': '10.1073/pnas.0701361104',
        'venue_name': 'Proceedings of the National Academy of Sciences',
        'venue_type': 'journal',
        'venue_year': 2007,
        'keywords': 'complex networks; bipartite graph; disease phenome; disease genes; human interactome; network medicine',
        'abstract': 'A network of disorders and disease genes linked by known disorder-gene associations offers a platform to explore in a single graph-theoretic framework all known phenotype and disease gene associations. We construct a bipartite graph linking genetic disorders with their associated causal genes, revealing shared genetic origins and disease-specific functional modules in the human interactome.',
        'datasets_used': 'Online Mendelian Inheritance in Man; Human Interactome Network',
        'dataset_domains': 'biomedical genetics; phenotype-genotype graphs',
        'methodology': 'Bipartite Network Projection; Topological Analysis',
        'methodology_category': 'Quantitative; Empirical Graph Modeling',
        'cited_paper_ids': 'P016',
        'page_count': 6,
        'language': 'English',
        'publisher': 'PNAS',
        'isbn_issn': '0027-8424',
        'pdf_filename': 'The Graph of Human Disease and Genetic Associations.pdf',
        'local_path': 'data/The Graph of Human Disease and Genetic Associations.pdf',
        'file_size_kb': 678,
        'scholar_url': 'https://scholar.google.com/scholar?q=The+Graph+of+Human+Disease+and+Genetic+Associations',
        'date_added': '2026-09-14',
        'notes': 'Landmark application of bipartite graph projection in biomedicine.'
    },
    {
        'paper_id': 'P018',
        'title': 'YAGO: A Core of Semantic Knowledge Unifying WordNet and Wikipedia',
        'authors': 'Fabian M. Suchanek; Gjergji Kasneci; Gerhard Weikum',
        'author_affiliations': 'Max-Planck-Institut für Informatik; Max-Planck-Institut für Informatik; Max-Planck-Institut für Informatik',
        'year': 2007,
        'doi': '10.1145/1242572.1242667',
        'venue_name': 'International World Wide Web Conference',
        'venue_type': 'conference',
        'venue_year': 2007,
        'keywords': 'knowledge base; semantic web; YAGO; ontology; Wikipedia; WordNet; information extraction',
        'abstract': 'We present YAGO, a large and extensible knowledge base with high precision. YAGO integrates the clean taxonomic backbone of WordNet with the broad coverage of Wikipedia entities and categories, yielding more than 1 million entities and 5 million facts represented as relational facts with 95 percent accuracy, formally defined with an expressive yet decidable logic model.',
        'datasets_used': 'WordNet 3.0; English Wikipedia Dump',
        'dataset_domains': 'lexical ontology; collaborative encyclopedia',
        'methodology': 'Information Extraction; Rule-Based Taxonomy Alignment',
        'methodology_category': 'Knowledge Engineering; Algorithmic',
        'cited_paper_ids': 'P001;P016',
        'page_count': 10,
        'language': 'English',
        'publisher': 'ACM',
        'isbn_issn': '1-59593-654-7',
        'pdf_filename': 'YAGO A Core of Semantic Knowledge.pdf',
        'local_path': 'data/YAGO A Core of Semantic Knowledge.pdf',
        'file_size_kb': 217,
        'scholar_url': 'https://scholar.google.com/scholar?q=YAGO+A+Core+of+Semantic+Knowledge',
        'date_added': '2026-09-14',
        'notes': 'Seminal knowledge graph unifying entities with relational facts.'
    }
]

fieldnames = [
    'paper_id', 'title', 'authors', 'author_affiliations', 'year', 'doi',
    'venue_name', 'venue_type', 'venue_year', 'keywords', 'abstract',
    'datasets_used', 'dataset_domains', 'methodology', 'methodology_category',
    'cited_paper_ids', 'page_count', 'language', 'publisher', 'isbn_issn',
    'pdf_filename', 'local_path', 'file_size_kb', 'scholar_url', 'date_added', 'notes'
]

output_path = 'papers.csv'
with open(output_path, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(papers_data)

print(f"Successfully generated {output_path} with {len(papers_data)} rows and {len(fieldnames)} columns.")
